{% set name = "cni-plugins" %}
{% set version = "0.7.5" %}
{% set cni_version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containernetworking/plugins/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 92c7599918be0a720ac020f137cdeac746dfa03da6b26e08a37132c5728c091f  # [not win]

build:
  skip: True  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - {{ compiler('c') }}  # [not win]
  host:
    - cni {{ cni_version }}
  run:
    - cni {{ cni_version }}

test:
  commands:
    - test -f $CNI_PATH/bridge

about:
  home: https://github.com/containernetworking/plugins
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Standard CNI network plugins, maintained by the containernetworking team.
  dev_url: https://github.com/containernetworking/plugins

extra:
  recipe-maintainers:
    - sodre
