travis:
  secure:
    BINSTAR_TOKEN: CDBFC8EV+CTy0665P5cqFh3WdHkXZfivVUVZfq60CI8w8GJfpaNSdkca216thxGF3ZvQ1C2UIfHLemUA/dePVQjNJI8um32iaODp6z/dXMqqA4QK4lbQSVt9rEC0AVOpcxWhG/keI9irXDP9gA4bykDXk1tUW9PhfMhAKY9/G1fL5Zvf2J3M9F06wsVwF0jr4QhSTGRWPWJz4tlC+V7eJ1i1RDPVZwcvEz5j1iLuB22txtn6ShTAlc9Yq/nZXHZz5I8nzWjXj2w4XfVuZU8+SUGYGkggKiZJ75BWL0k5NR4txhRvD+tlCNcyCUE92CCfgMxegkhiUKuNCVXnv0d+vgdZAoerOucl5a3C+iUNDA3RVHSmGkcQN3B5uDtJ9Nd1przfsrHl8qnMVnRbnmn5EtkeCpY2QLMhsLkSy2C9enYCXveLaPHtfJ3i2WKpmWa0bBE5xjLpN//1XKhluLHM7GPzkiXsU9cJuEZ9RdVu5ekerZSfg9pFRtF5ImRF5wIOhgufC7CME2WAUhn9Yed5fMkv+6BTPRErOO1S7dMOOHDrp8gOn6gWHSG9P1eQ6O3YRPczAUVFJU6D5OfzN5ppPaSzJOwoQXgsGRFNnxsNi1xPQvlazMmrvlbhWyWaOk8xvNXSIwW0gpJgXFrzt4C0BMNAWrix0dNDfGLsOhRli5c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
