travis:
  secure:
    BINSTAR_TOKEN: Xjm4mqQhJj3eXnHgya9lpjs9RRMvXbDP2r+OeHFP5AXzi0L3ihYg17A1eGXzy+bKxuoSaQ4shxtKZa6uSLXRwEERTI490DC8sKJJWF/aa0sHaFuGpAybaATKk/TUlgD5AS6qaZZQcYh/CHt584uw769mFRLkfkML0JDokFj10c//Wjk0pNTM+VeYxO/R66nyg7FpIHw6AFbR5nGzUEDbN5VMOlhj7L7jrB8dzg22X9Jfu3NGbEPw2Ehx1lbiwBuB7wgUMNVizqlFaXaaUy0T7SPA0EriuDQgoi0PZ0qxxK4FHf+DPllQdPkMnL7KNHpnWMxtM+xBDuGK12QWjvznFMeAsHoA0+vBJ1Dpum2JPQC59a4Uq16KyJ2Ld0Flmgk376hQ8dcridMX80sFMpdJNKJrrWN7LSKfxaW0L9hkBjNWGpztMswhI/w8j/38AzlXkjLOh8Efs82HM6QMSWv9ru95PrYEHoVil1jy2dpOwQX0R9KwstK+SQSNtEcg6C9iq+dDeY/l6HIcvK083aIjgPnX0gcfhm2W+VguSonX6dQ9X5qsD2GZ+xeIRcChQ1FWZrETSREpupUBOwJgdVClfOG13C9GVlRbNK1l4GfcFQXlcNnPr7VfzAmzdOkmWhzmZ9S/F22Px6v+BUaqX/YX+ihRfVnuGPFk0wBKy6WsI74=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
