travis:
  secure:
    BINSTAR_TOKEN: RKnY2PoUUjz0ZIECYEOlsUX3G74rdV7iDBekn7c0JdNQmXRvVj8m+hDXlwcey74hnH3jsAnYGyow0ZfuzqK4HVxlk0z1c2rMnzD7RcOdVMUb36kX12r6UtBCix0uDzaNo4YeKVPkFX7CsHABxDJPoeeWvfPoJhc2JNNxWJBhlkHJ9pqQlpIvpjC58+cQkhvB2MO+ICL8/+kMXynMFp8c4Ky1QMjwHGqF4MD7XeMmmeohYWOi+6AUAk8D8no3K3JFUTDuTbHkJNN3H0+8QkqocNcscTy6lZTdbSvXaNW3Xm0i/h1Y4V2oly9uUbG+c6NqY84g9DDvT6qtw+6FAhtKvzQ5QntEg8hSZSBPYJsoVy5/w3nMhJQhxm14YvbTgJIJcI2dn4N1RYe384dgoAh7unvMs6bZTQodlgYp3IuhfvQw5lKhxhIE3wE/jmUF/ljfFiGiEmzp9q5etzFhHFSq/gBxyAmPjPRVNA2eu4jmsSArhbx0czsVqUOOp0LXB1E5t4d/nx6yd5eaoK4NqPBZePCQTKJM5FOvDKBGLa7uhLg2Zn1zYfdwoff3n1+eYbgrzU5MWebUjYptPZG9Eb3J1t1kbrhT/VVqm8StkDPQeqCrmvSxeEEg0Pe/XtiSXotmRs8rEwcxTMHQiGEE7MuSSBoOZsWWsP1xv9kIWLg1vVk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
